REM @echo off

echo // generated by version_update.bat > ..\DiaryEditor\Version.h
IF DEFINED APPVEYOR (
    echo #define DE_VERSION "%APPVEYOR_BUILD_VERSION%" >> ..\DiaryEditor\Version.h 
    echo Building Diary Editor %APPVEYOR_BUILD_VERSION%...
) ELSE (
    echo #define DE_VERSION "LocalBuild" >> ..\DiaryEditor\Version.h
)

:exit